### ISSUE TITLE
Make ImageSurface::get_data immutable

### ISSUE THREAD

**Issue by RazrFalcon** [gtk-rs/cairo#279]
Currently, this method requires `&mut self`, which is useful to prevent multiple borrows, but it still doesn't have a 100% guarantee. Therefore it returns `Result`.

The problem is that you have to have a mutable `ImageSurface` to get an immutable data.

Maybe we should split it into `get_data` and `get_data_mut`?

**Comment by sdroege** [comment]
>Maybe we should split it into `get_data` and `get_data_mut`?

How would the immutable one work differently? You still need to ensure that you have the only reference or otherwise whoever has the other references (e.g. inside Cairo, gtk, ...) could modify the data while you have the immutable reference to it.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RazrFalcon** [comment]
It will also return `Result`, but data will be read-only.

**Comment by sdroege** [comment]
>It will also return `Result`, but data will be read-only.

That would work but be unsafe as afterwards you could still pass references to other code and do mutable operations on the data... While you have a immutable reference to it still.

We must ensure that while we have a reference to the data nothing else can get a mutable or immutable reference to it anymore, or otherwise it might get modified behind our back. And the mutable borrow ensures that.


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdroege** [comment]
Asked differently, why do you want this new function? What's the use case where you can't use the current one?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by RazrFalcon** [comment]
It's hard to explain my exact case, but the point is that there should be a method that will return a read-only data. Currently it's not possible.

>And the mutable borrow ensures that.

It doesn't. We still checking refcounting.

**Comment by sdroege** [comment]
>It's hard to explain my exact case, but the point is that there should
>be a method that will return a read-only data. Currently it's not
>possible.

A mutable reference can be transparently converted to an immutable one. Pass it along as immutable reference if that's what you need.

>>And the mutable borrow ensures that.
>
>It doesn't. We still checking refcounting.

That's not the point. For getting the data there's no other way then checking the refcount.

But after returning a reference to the data the mutable borrow ensures that nothing gets any reference to the surface while you have a reference to the data.

It would be unsafe with an immutable borrow for that very reason.


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdroege** [comment]
Basically, do you need a `fn get_data(&self) -> Result<&[u8], _>` or a `fn get_data(&mut self) -> Result<&[u8], _>`? The first is unsound, the second is equivalent to the current function.

**Comment by RazrFalcon** [comment]
I do not understand why the first one is unsound.

**Comment by sdroege** [comment]
```rust
let surface = ...;
let data = surface.get_data().unwrap();
// you have an immutable reference to the data now
let cr = cairo::Context::new(&surface);
// now you can modify the surface data via the context while still having an immutable reference to the data
```

**Comment by RazrFalcon** [comment]
Thanks. Than I will use a mutable reference.
